spring:
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
server:
  address: 0.0.0.0
  port: 3333

node:
  # List of peer addresses (host:port)
  peers:  []  
  wallet-password: changeMeSuperSecret

