spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:3333}

node:
  peers: []
  data-path: data
  wallet-password: ${NODE_WALLET_PASSWORD:changeMe}
  jwt-secret:    ${NODE_JWT_SECRET:changeMeSuperSecret}

wallet:
  store-path: .simple-chain/wallet.p12

mempool:
  maxSize: 1000
