spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  address: 0.0.0.0
  port: 3333

node:
  peers: []
  wallet-password: ${NODE_WALLET_PASSWORD:changeMe}
  jwt-secret:    ${NODE_JWT_SECRET:changeMeSuperSecret}

mempool:
  maxSize: 1000
