# application.yaml  –  Default-Werte
node:
  role: FULL                 # FULL | MINER | LIGHT
  host: localhost
  bootstrap: []              # List<URI>
  sync-interval-ms: 30000

  mining:                    # nur MINER
    enabled: false           # wird per Rolle automatisch überschrieben
    interval-ms: 10000

  storage:                   # nur LIGHT
    prune-after-blocks: 2016
