services:
  backend:
    image: blockchain-node:latest
    env_file: .env
    environment:
      NODE_WALLET_PASSWORD: "${NODE_WALLET_PASSWORD}"
      NODE_JWT_SECRET:     "${NODE_JWT_SECRET}"
      NODE_PEERS:          "${NODE_PEERS}"
      SERVER_PORT:         "${BACKEND_PORT}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        VITE_NODE_URL: http://localhost:${BACKEND_PORT}/api
        VITE_NODE_WS: ws://localhost:${BACKEND_PORT}/ws
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    env_file:
      - .env   # optional, wenn du noch Runtime-ENV im Container brauchst
    restart: unless-stopped
