/*
 * This source file was generated by the Gradle 'init' task
 */
package simple.blockchain;

import simple.blockchain.architecture.Block;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Block block = new Block();
    }
}
