# .github/workflows/ci.yml
name: Java&nbsp;CI

on:
  push:
    branches: [ "main" ]   # adjust if you use a different default branch
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ "17" ]   # add more versions if you want a matrix

    steps:
    - name: ⬇️  Checkout sources
      uses: actions/checkout@v4

    - name: Set up Temurin JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}
        cache: gradle              # enable Gradle build‑cache between runs

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build & test (Gradle)
      run: ./gradlew clean jacocoTestReport --no-daemon

    - name: Upload node JAR (artifact)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: blockchain-node-jar
        path: blockchain-node/build/libs/**/*.jar

    - name: Upload core JAR (artifact)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: blockchain-core-jar
        path: blockchain-core/build/libs/**/*.jar

    - name: Start Selenium container
      run: docker run -d --name selenium -p 4444:4444 selenium/standalone-chrome

    - name: Build & start multi-node setup
      run: docker compose -f docker-compose.ci.yml up -d --build --wait

    - name: Run end-to-end tests
      run: |
        pip install selenium requests PyJWT behave grpcio protobuf
        behave pipeline-tests/e2e.feature

    - name: Stop containers
      if: always()
      run: |
        docker compose -f docker-compose.ci.yml down
        docker rm -f selenium
