name: CI

on:
  push:
    branches: [ "main", "work" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Python deps
        run: pip install pytest PyYAML
      - name: Run pipeline
        run: make ci
